import json,hashlib,shutil
from pathlib import Path
R=Path.cwd();O=R/'outputs/game';O.mkdir(exist_ok=True);(O/'motion').mkdir(exist_ok=True)
SPECS=[('A',R/'outputs/experiment/body_data/A_rtmw_133.json',R/'outputs/expanded/identity/A-identities.json',{'fighter_green':'Alex Pereira','fighter_yellow':'Israel Adesanya'},'../experiment/clips/A.mp4',None,'Long-limbed standing exchanges. Watch how each fighter manages the space.'),('E',R/'outputs/expanded/body_data/E_rtmmw_133.json',R/'outputs/expanded/identity/E-identities.json',{'fighter_cyan':'Alex Pereira','fighter_coral':'Israel Adesanya'},'../expanded/clips/E.mp4',None,'Hand positioning and distance changes are visible; contact often remains unclear.'),('B',R/'outputs/experiment/body_data/B_rtmw_133.json',R/'outputs/expanded/identity/B-identities.json',{'fighter_green':'Conor McGregor','fighter_black':'Khabib Nurmagomedov'},'../experiment/clips/B.mp4',2018,'Before the bodies overlap, the standing movement is easier to recognize.'),('F',R/'outputs/expanded/body_data/F_rtmw_133.json',R/'outputs/expanded/identity/F-identities.json',{'fighter_cyan':'Alex Pereira','fighter_coral':'Israel Adesanya'},'../expanded/clips/F.mp4',None,'The fence exchange makes limb ownership harder. Missing tracks stay missing.')]
SPECS[1]=tuple(str(x).replace('rtmmw','rtmw') if isinstance(x,str) else Path(str(x).replace('rtmmw','rtmw')) if isinstance(x,Path) else x for x in SPECS[1])
for c,year,opp,insight in [('P',2012,'Ivan Buchinger','Kicks, retraction and distance resets give this exchange its rhythm.'),('Q',2013,'Max Holloway','Shuffle → long punching entry → stance recovery → withdrawal.'),('R',2018,'Khabib Nurmagomedov','Short repositioning and hand probing; foot visibility limits the reading.'),('S',2021,'Dustin Poirier','Punch-led pursuit, with repeated forward steps toward the fence.')]:
 base=R/'outputs/expanded/mcgregor/tracked';SPECS.append((c,base/'body_data'/f'{c}_rtmw_133.json',base/'identity'/f'{c}-identities.json',{'fighter_cyan':'Conor McGregor','fighter_coral':opp},f'../expanded/mcgregor/four_bout/clips/{year}-native-standing.mp4',year,insight))
rounds=[];excluded=[]
for cid,posepath,idpath,names,video,year,insight in SPECS:
 p=json.loads(posepath.read_text());ids=json.loads(idpath.read_text());keys=list(names);duration=p['frames'][-1]['time']+1/p['fps'];starts=list(range(0,17,2)) if duration>10 else [0,2,4];length=4 if duration>10 else 3.5
 for start in starts:
  subset=[(j,f) for j,f in enumerate(p['frames']) if start<=f['time']<min(duration,start+length)];both=sum(len({z['identity'] for z in ids['frames'][j]['people'] if z['identity'] in keys})==2 for j,f in subset)/len(subset)
  if both<.74:excluded.append({'source':cid,'start':start,'both_fighters_coverage':both});continue
  number=len(rounds)+1;name=f'r{number:02d}';frames=[];allxy=[]
  for j,f in subset:
   people=[]
   for z in ids['frames'][j]['people']:
    if z['identity'] not in keys:continue
    k=f['people'][z['detection_index']]['keypoints'];pts=[[round(x,1),round(y,1)] if sc>=2 and 0<=x<p['width'] and 0<=y<p['height'] else None for x,y,sc in k];allxy.extend(q for q in pts[:23] if q);people.append({'role':keys.index(z['identity']),'points':pts})
   frames.append({'t':round(f['time']-start,4),'people':people})
  assert allxy;xs,ys=zip(*allxy);bbox=[max(0,min(xs)-30),max(0,min(ys)-30),min(p['width'],max(xs)+30),min(p['height'],max(ys)+30)];motion={'width':p['width'],'height':p['height'],'duration':round(min(length,duration-start),4),'fps':p['fps'],'bounds':bbox,'frames':frames};(O/'motion'/f'{name}.json').write_text(json.dumps(motion,separators=(',',':')));rounds.append({'id':name,'motion':f'motion/{name}.json','names':[names[k] for k in keys],'video':video,'start':start,'duration':motion['duration'],'year':year,'insight':insight,'quality':round(both,3),'source_id':cid})
manifest={'rounds':rounds,'roster':sorted({n for r in rounds for n in r['names']}),'peter':'https://pwang724.github.io/tennis-skeleton-quiz/','limits':'Recognition game from a small repeated-bout collection. Color swaps per round. Missing/ambiguous identities excluded; same-model anchors are not perfect identity truth.'};(O/'manifest.json').write_text(json.dumps(manifest,separators=(',',':')));(O/'build-audit.json').write_text(json.dumps({'rounds':len(rounds),'sources':len(SPECS),'excluded_windows':excluded,'gate':'Both clothing roles associated in >=74% of sampled frames; candidate points raw score>=2 and in image bounds','source_hashes':{str(p.relative_to(R)):hashlib.sha256(p.read_bytes()).hexdigest() for s in SPECS for p in [s[1],s[2]]}},indent=2));print('GAME POOL',len(rounds),'rounds',len(manifest['roster']),'fighters',len([r for r in rounds if r['source_id'] in 'PQRS']),'era windows')
