from pathlib import Path
import json,shutil
O=Path('outputs/game');m=json.loads((O/'manifest.json').read_text());count=len(m['rounds']);era=sum(r['source_id'] in 'PQRS' for r in m['rounds'])
p=O/'game.css';s=p.read_text();s=s.replace('--paper:#edece5;--ink:#172b3a;--blue:#263fb2;--deep:#182a71;', '--paper:#000000;--ink:#f1f0e9;--blue:#a3bcc2;--deep:#111111;').replace('--line:#c3c7bf;--quiet:#667268','--line:#303236;--quiet:#a0a5aa').replace('background:var(--blue);overflow:hidden','background:#000;overflow:hidden').replace('background:#d5d9d1','background:#26292d').replace('color:#dce5ff','color:#aeb7bf').replace('background:#182a7188','background:#000b').replace('background:#263fb20a','background:#ffffff08').replace('background:var(--blue)}.fine','background:#b8d0d6}.fine')
for color in ['#607065','#6d776b','#687668','#667268','#778071','#687566','#8b9388']:s=s.replace(color,'#a0a5aa')
s=s.replace('color:#438060','color:#83c89d').replace('color:#b05338','color:#ffad8e');p.write_text(s)
p=O/'game.js';s=p.read_text().replace("ctx.fillStyle='#263fb2'", "ctx.fillStyle='#000000'").replace("ctx.strokeStyle='#a8b8ff18'", "ctx.strokeStyle='#ffffff18'").replace('ghostfight.active.v1','ghostfight.strikes.active.v1').replace('ghostfight.best.v1','ghostfight.strikes.best.v1').replace("mode==='eras'?8:mode==='championship'?24:12", "mode==='eras'?Math.min(8,pool.length):mode==='championship'?pool.length:Math.min(8,pool.length)").replace("$('status').textContent='Motion failed to load.'", "$('watchStatus').textContent='Motion failed to load.'").replace("m.rounds.length+' motion windows · '","m.rounds.length+' strike exchanges · '")
s=s.replace("manifest=m;$('poolInfo')", "manifest=m;document.querySelector('[data-mode=championship] span').textContent=m.rounds.length+' rounds · every strike exchange';document.querySelector('[data-mode=eras] span').textContent=m.rounds.filter(r=>'PQRS'.includes(r.source_id)).length+' rounds · guess the era';document.querySelector('footer span').textContent=m.rounds.length+' curated strike exchanges · '+m.roster.length+' fighters';$('poolInfo')")
p.write_text(s)
p=O/'index.html';s=p.read_text().replace('12 rounds · both fighters','8 rounds · both fighters').replace('24 rounds · the long test',f'{count} rounds · every strike exchange').replace('8 rounds · guess the era',f'{era} rounds · guess the era').replace('27 motion windows · 7 fighters · a small, repeated-bout collection',f'{count} curated strike exchanges · 7 fighters').replace('Two fighters. Only dots and lines.','Real strikes. Only dots and lines.');p.write_text(s)
p=O/'README.txt';s=p.read_text().replace('12-round Fight card,24-round Championship,8-round McGregor era challenge',f'8-round Fight card,{count}-round Championship,{era}-round McGregor era challenge').replace('27 motion windows,7 fighters,8 source clips',f'{count} curated strike exchanges,7 fighters,7 source clips').replace('windows overlap and repeated fighters/opponents provide clues','one window per selected committed attack or exchange; repeated fighters/opponents provide clues');s+='\nBlack background throughout. strike-selection.json records every selected strike interval and reviewed label source. Quiet probes, reset-only windows and ambiguous attempts were removed; contact or damage is not inferred from inclusion.\n';p.write_text(s)
shutil.copy2('work/game/build_game.py',O/'reproduce/build_game.py')
# Validate the selected attacks are inside their windows and tracked at attack time.
for r in m['rounds']:
 motion=json.loads((O/r['motion']).read_text());attack=[f for f in motion['frames'] if r['strike_start']<=f['t']<=r['strike_end']];assert attack;both=sum(len({p['role'] for p in f['people']})==2 for f in attack)/len(attack);print(r['id'],r['source_id'],'strike frames',len(attack),'both tracks',round(both,2));assert both>=.5
