from pathlib import Path
import json,cv2
R=Path.cwd();O=R/'outputs/expanded';D=O/'frame_lab';D.mkdir(exist_ok=True);rows=[]
for c in 'EFGHIJ':
 a=json.load(open(O/'annotations'/f'{c}.json'));b=json.load(open(O/'annotations'/f'{c}_detail.json'));m=next(x for x in (json.load(open(O/'annotation_manifest.json'))+json.load(open(O/'annotation_manifest_extra.json'))) if x['id']==c)
 rows.append({'clip':c,'manifest':m,'reviewed':a,'detail':b,'native_review_spans':json.load(open(O/'evidence'/c/'dense_manifest.json'))})
(D/'data.json').write_text(json.dumps(rows,indent=2))
html='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MMA Frame Laboratory</title><style>
:root{--bg:#10171c;--panel:#18232a;--ink:#edf0e9;--muted:#a3b0b7;--cyan:#22d3ee;--coral:#fb7185}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 system-ui}main{max-width:1450px;margin:auto;padding:30px}a{color:var(--cyan)}h1{font-size:clamp(34px,4vw,54px);letter-spacing:-1.7px;font-weight:550;margin:12px 0}p{color:var(--muted)}.kicker{font-size:12px;letter-spacing:2px;color:var(--cyan)}.grid{display:grid;grid-template-columns:1.25fr 1fr;gap:22px}.card{background:var(--panel);padding:18px;border:1px solid #35434a;border-radius:12px}.stage{position:relative}video{width:100%;display:block;background:black}#zoom{position:absolute;right:12px;bottom:12px;width:35%;border:1px solid var(--cyan);background:black;pointer-events:none;display:none}.controls{display:flex;flex-wrap:wrap;gap:7px;margin:14px 0}button,select,input{font:inherit;background:#1c2a33;color:var(--ink);border:1px solid #485e69;border-radius:5px;padding:8px}input[type=range]{width:100%;padding:0}button{cursor:pointer}button:hover{border-color:var(--cyan)}#time{font:13px monospace;color:var(--cyan)}.roles{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:14px}.dot{width:10px;height:10px;border-radius:50%;display:inline-block;margin-right:6px}.event{border-left:2px solid var(--cyan);margin:14px 0;padding:8px 12px;background:#14242c}.correction{border-left:2px solid var(--coral);padding:10px 14px;margin:12px 0;background:#251f28}.small{font-size:12px;color:var(--muted)}.track{height:26px;background:#27333b;position:relative;margin:12px 0;cursor:pointer}.span{position:absolute;height:100%;background:#22d3ee55;border-left:1px solid var(--cyan)}#needle{position:absolute;height:100%;width:2px;background:white}.timeline-label{display:flex;justify-content:space-between;font-size:12px;color:var(--muted)}.filmstrip{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:12px}.filmstrip button{padding:0;border:0;position:relative}.filmstrip img{width:100%;display:block}.filmstrip span{display:block;font:11px monospace;background:#162832;padding:4px}pre{font:12px/1.5 monospace;white-space:pre-wrap;overflow-wrap:anywhere}details{margin-top:16px}summary{color:var(--cyan);cursor:pointer}.toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.note{border-left:2px solid var(--coral);padding:10px 15px;margin:20px 0;background:#1c232a}.claim{border-bottom:1px solid #34464f;padding:10px 0}#panel{max-height:850px;overflow:auto}@media(max-width:850px){.grid{grid-template-columns:1fr}main{padding:18px}#panel{max-height:none}}
</style></head><body><main><a href="../index.html">← Evidence laboratory</a><div class="kicker">NATIVE FRAMES / ACTION / RESPONSE / CORRECTION</div><h1>Look closer. Keep the uncertainty.</h1><p>A frame-level bench for the richly reviewed sequences. Explore movement, body contact, grip changes, and the exact places where a later review challenged an earlier label.</p><div class="toolbar"><select id="case" aria-label="Choose clip"></select><div class="roles" id="roles"></div></div><div class="grid"><section class="card"><div class="stage"><video id="v" muted playsinline controls preload="metadata"></video><canvas id="zoom" width="480" height="270"></canvas></div><div class="controls"><button id="back">← Frame</button><button id="forward">Frame →</button><button id="play">Play / pause</button><select id="speed" aria-label="Playback speed"><option value=".1">0.1×</option><option value=".25">0.25×</option><option value=".5">0.5×</option><option value="1" selected>1×</option></select><button id="magnify">Magnifier off</button></div><div id="time"></div><input id="seek" type="range" min="0" max="19.96" step=".01" value="0" aria-label="Clip time"><div class="small">Cyan spans: native-rate fine-detail review windows. Gaps retain sparse discovery observations. Click a span or an event to inspect it.</div><div class="track" id="track"></div><div class="timeline-label"><span>0 seconds</span><span>20 seconds</span></div><div class="filmstrip" id="film"></div><p class="small">Frame stepping uses the native frame interval and browser seeking; timestamps are approximate. Magnification enlarges existing pixels. It adds no detail or inferred anatomy. Keyboard: ← / →, space.</p></section><section class="card" id="panel"><div id="context"></div><h2>Latest frame review</h2><div id="detail"></div><h2>Earlier events & later corrections</h2><div id="events"></div><details><summary>Full traceable annotation data</summary><pre id="raw"></pre></details></section></div><div class="note">These are independent model reviews, not expert-certified ground truth. Contact may be a grip or body-control connection. It does not establish a landed strike, clean contact, force, or damage. Later corrections are displayed alongside earlier records; prose fields have not been silently merged into a new canonical truth.</div><a href="data.json">Download review data</a></main><script>
const DATA=__DATA__,$=x=>document.getElementById(x),v=$('v'),z=$('zoom'),ctx=z.getContext('2d');let magnify=false,pointer={x:.5,y:.5},active='',lastFilm=-1;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pretty=x=>esc(typeof x==='string'?x:JSON.stringify(x,null,2));function current(){return DATA[Number($('case').value)]}function seek(t){v.pause();v.currentTime=Math.max(0,Math.min(v.duration||20,t));renderTime()}function correction(e,d){return(d.detail.corrections||[]).filter(c=>c.event_id===e.id).map(c=>`<div class="correction"><strong>Later review · ${esc(c.field)}</strong><p>${esc(c.new)}</p><div class="small">${esc(c.reason)}</div><details><summary>Earlier wording</summary>${pretty(c.old)}</details></div>`).join('')}
function renderTime(){let d=current(),t=v.currentTime||0;$('seek').value=t;$('time').textContent=`Clip ${d.clip} · ${t.toFixed(3)}s · source ${(d.manifest.source_offset+t).toFixed(3)}s`;$('needle').style.left=100*t/20+'%';let ws=d.detail.window_reviews.filter(w=>t>=w.start-.035&&t<=w.end+.035);$('detail').innerHTML=ws.length?ws.map(w=>`<div class="event"><strong>${w.start.toFixed(3)}–${w.end.toFixed(3)}s</strong>${w.observable_cues.map(x=>`<p>${esc(x)}</p>`).join('')}${w.contact_claims.map(c=>`<div class="claim"><strong>${esc(c.actor||'Actor not specified')} · ${esc(c.contact_kind)}</strong><p>${esc(c.contact)}${c.target?' → '+esc(c.target):''}</p><div class="small">${esc(c.certainty)}</div></div>`).join('')}<details><summary>Visibility & uncertainty</summary><pre>${pretty({visibility:w.visibility,uncertainties:w.uncertainties})}</pre></details></div>`).join(''):'<p>No native-rate fine-detail window covers this instant. Inspect the broader discovery observations below.</p>';
let es=d.reviewed.events.filter(e=>t>=e.start-.1&&t<=e.end+.1);$('events').innerHTML=es.length?es.map(e=>`<div class="event"><button data-t="${e.start}">${esc(e.id)} · ${e.start.toFixed(2)}s</button><strong> ${esc(e.actor)}</strong><p>${esc(e.action)}</p><div>${esc(e.response||e.visible_outcome||'')}</div><p class="small">Earlier contact label: ${esc(e.contact)} · ${esc(e.contact_scope||e.verification||e.limits||'')}</p>${correction(e,d)}</div>`).join(''):'<p>No earlier event interval covers this instant.</p>';$('events').querySelectorAll('button[data-t]').forEach(b=>b.onclick=()=>seek(Number(b.dataset.t)));const s=d.reviewed.segments.find(s=>t>=s.start&&t<=s.end);$('context').innerHTML=s?`<h2>${esc(s.phase||'Visible position')}</h2><p>${esc(s.position||s.movement||s.discovery_observations||'')}</p>`:'';if(magnify&&v.readyState>=2){let ww=v.videoWidth/3,hh=ww*9/16;ctx.drawImage(v,Math.max(0,Math.min(v.videoWidth-ww,pointer.x*v.videoWidth-ww/2)),Math.max(0,Math.min(v.videoHeight-hh,pointer.y*v.videoHeight-hh/2)),ww,hh,0,0,480,270)}if(Math.floor(t)!==lastFilm){lastFilm=Math.floor(t);drawFilm(d,t)}}
async function drawFilm(d,t){const cid=d.clip;let times=[Math.max(0,t-.15),Math.max(0,t-.05),Math.min(19.96,t+.05),Math.min(19.96,t+.15)];$('film').innerHTML=times.map((s,i)=>`<button data-t="${s}"><img src="frames/${cid}_${Math.round(s*30).toString().padStart(4,'0')}.jpg" alt="Nearby native frame"><span>${s.toFixed(3)}s requested</span></button>`).join('');$('film').querySelectorAll('button').forEach(b=>b.onclick=()=>seek(Number(b.dataset.t)))}
function change(){v.pause();let d=current();v.src='../clips/'+d.clip+'.mp4';lastFilm=-1;$('roles').innerHTML=d.reviewed.fighters.map(f=>`<span><i class="dot" style="background:${f.display_hex}"></i>${esc(f.id)}</span>`).join('');$('track').innerHTML=d.native_review_spans.map(w=>`<span class="span" style="left:${100*w.start/20}%;width:${100*(w.end-w.start)/20}%" title="${w.start}–${w.end}s"></span>`).join('')+'<span id="needle"></span>';$('raw').textContent=JSON.stringify(d,null,2);renderTime()}
$('case').innerHTML=DATA.map((d,i)=>`<option value="${i}">Clip ${d.clip} · ${d.manifest.source.replaceAll('-',' ')}</option>`).join('');$('case').onchange=change;$('back').onclick=()=>seek(v.currentTime-1/current().manifest.source_fps);$('forward').onclick=()=>seek(v.currentTime+1/current().manifest.source_fps);$('play').onclick=()=>v.paused?v.play():v.pause();$('speed').onchange=()=>v.playbackRate=Number($('speed').value);$('seek').oninput=()=>seek(Number($('seek').value));$('track').onclick=e=>{let r=e.currentTarget.getBoundingClientRect();seek(20*(e.clientX-r.left)/r.width)};$('magnify').onclick=()=>{magnify=!magnify;z.style.display=magnify?'block':'none';$('magnify').textContent='Magnifier '+(magnify?'on':'off');renderTime()};v.onpointermove=e=>{let r=v.getBoundingClientRect();pointer={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};renderTime()};v.ontimeupdate=renderTime;v.onseeked=renderTime;document.onkeydown=e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;if(e.key==='ArrowLeft'){$('back').click();e.preventDefault()}if(e.key==='ArrowRight'){$('forward').click();e.preventDefault()}if(e.code==='Space'){$('play').click();e.preventDefault()}};change();
</script></body></html>'''
# Filmstrip is authentic decoded 30Hzindex proxy; metadata carries exactnativefps.
F=D/'frames';F.mkdir(exist_ok=True)
for d in rows:
 cap=cv2.VideoCapture(str(R/d['manifest']['clip']));fps=cap.get(5)
 for ix in range(600):
  p=F/f"{d['clip']}_{ix:04d}.jpg"
  if p.exists():continue
  cap.set(cv2.CAP_PROP_POS_FRAMES,min(int(cap.get(7))-1,round(ix/30*fps)));ok,f=cap.read()
  if ok:cv2.imwrite(str(p),cv2.resize(f,(384,216)),[cv2.IMWRITE_JPEG_QUALITY,78])
 cap.release()
(D/'index.html').write_text(html.replace('__DATA__',json.dumps(rows).replace('</','<\\/')))
print('FRAME LAB BUILT')
