import json,datetime,html,collections
from pathlib import Path
R=Path.cwd();O=R/'outputs/expanded';D=O/'assessment';D.mkdir(exist_ok=True)
GRADES=[
('Native evidence browsing and exchange stories','A','Useful now','Timestamped frames, slow motion, action/response records, and visible later corrections make an engaging review experience. Keep uncertain actions explicit; each claim links to pixels.','Model-reviewed evidence is not expert-certified truth.','../frame_lab/index.html'),
('Coarse phase and broad positional labels','B','Good in these clips','Standing, clinch, ground, top/bottom, and fence engagement are often visible even when fine anatomy is hidden.','No population annotation-accuracy estimate; subtle guard/grip labels need separate evidence.','../annotations/E.json'),
('Colored standing whole-body animation','B','Promising constrained demo','New standing clip E associates435/482 detector candidates to clothing roles.133-point figures include face, hand and foot estimates.','Coverage is not identity accuracy. Occluded joints, finger geometry under gloves and native12Hz pose jitter remain unverified. Render uncertain bodies gray; offer figure-only inspection.','../motion.html'),
('Clinch and ground anatomical reconstruction','D','Whole-body ownership remains unreliable','NewF/G/H clothing association is170/463,3/594,0/769 respectively. Mask variants achieve a few supported head/glove/knee improvements.','Masks can erase own limbs or retain opponent limbs. A local correct glove does not validate a whole hand or skeleton. Better combat-aware temporal joint ownership and better views are needed.','../segmentation/review/safer/review-summary.txt'),
('Visible strike attempts and strike-type labels','B/C','Standing stronger; ground conditional','Dense frames can establish commitment and reset without claiming contact. A native H8 review supports a late new ground punch before12s.','GradeB for clear visible attempts; C for crowded/ambiguous cases. Probe, grip and strike can resemble one another. More dense review helps some cases; hidden endpoints remain unknown.','../key_moments/native_review/H_8_onset_supplement.json'),
('Contact versus miss','C','Only where visible','Visible body/grip connection is frequently labelable; visible separation can support a miss when the complete strike trajectory is exposed.','Supported body contact is not a landed strike. Current richreview has no verified miss events; contact accuracy is not established.','../research_bundle.json'),
('Clean hit versus block; force, damage, accuracy stats','D','No reliable claim from this study','Possible future experience: show observable recoil, balance loss or knockdown as distinct visible outcomes, with source evidence.','Do not turn image proximity or recoil into physical force/tissue damage. Strike accuracy needs trustworthy attempt and contact denominators. Highfps/multiple views and verified outcomes are more valuable than more confident prose.','../frame_lab/index.html'),
('McGregor style time machine','B','Useful comparison now','Four bouts2012/2013/2018/2021,28reviewedwindows, chronological native videos, feet/identity exposure gates, repeated sampling checks and visible-landmark measurements.','Image-plane ratios vary with camera angle and within bouts. The karate-to-boxing hypothesis remains unproven;2012is earliest downloaded,2021latest downloaded, neither career endpoint.','../mcgregor/four_bout/index.html'),
('Quantified career change or fighter progression','C','Needs matched longitudinal coverage','A rigorous study can quantify visible footwork, stance, guard, action repertoire and responses under comparable phase/distance/view conditions.','More bouts and comparable annotated exposure; chronological dates, opponent/context/round confounds; uncertainty-aware measurements. Do not fit a career narrative to selected highlights.','../mcgregor/four_bout/findings.txt'),
('Educational freeze-and-guess experience','A','Delightful as an experiment','Freeze a clip, inspect past-only forecasts, reveal the next four seconds, and see when the model is surprised.','Product appeal is separate from predictive validity. Label disagreement and selected stress cases stay visible.','../key_moments/index.html'),
('Trustworthy anticipation of surprising key moments','D','Not demonstrated','The original/rich/pose conditions miss the selected takedown at all3cutoffs; originalrich probabilities are12%,15%,13%, subject to actualrawdata inspection. Reversal stress is also difficult.','Common event continuation differs from useful early warning. Need independent positive episodes and true-negative windows, onset-based warning metrics, chronological/heldout-bout evaluation and better causal state representations. No training performed.','../key_moments/stratified_scores.json'),
('Submission detection and prediction','D','Positive detection untested','Submission-entry probabilities and uncertainty are recorded separately.','No verified positive submission-entry episode in the main study. High guard or neck engagement alone does not establish an attack. Need clearly visible positive/negative references.','../key_moments/protocol.json'),
('Fight-winner prediction and damage/bleeding inference','D','Untested or inadequate evidence','These remain possible research directions if full temporal outcome data and reliable visible observations are collected.','Short selected clips cannot validate fight-winning predictions. Blood candidate false positives on red graphics/clothing were observed; no validated sensitivity.','../morning-report.txt')]
# Correct literalraw takedownprobabilities fromactualdata rather than editorialmemory.
ps={}
for t in [4,6,7]:
 p=O/'key_moments/predictions'/f'B_{t}_rich_history.json'
 if p.exists():ps[t]=json.load(open(p))['probabilities']['takedown_attempt']
if len(ps)==3:
 row=list(GRADES[10]);row[3]='All original/rich/pose conditions miss the selected takedown at all3cutoffs. Original rich-history probabilities: '+', '.join(f'{100*ps[t]:.0f}% at{t}s' for t in [4,6,7])+'. Reversal stress is also difficult. Dense causal review is tested separately.';GRADES[10]=tuple(row)
count={'decoded_sources':len(json.load(open(O/'source_inventory.json'))),'scout_windows':len(json.load(open(O/'scout_manifest.json')))+len(json.load(open(O/'new_scout_manifest.json'))),'rich_clips':[],'events':0,'disagreement_records':0,'fine_detail_corrections':0,'contact_status_counts':collections.Counter()}
for c in 'EFGHIJ':
 p=O/'annotations'/f'{c}.json';q=O/'annotations'/f'{c}_detail.json'
 if p.exists():
  a=json.load(open(p));count['rich_clips'].append(c);count['events']+=len(a.get('events',[]));count['disagreement_records']+=len(a.get('disagreements',[]));count['contact_status_counts'].update(e.get('contact','unspecified') for e in a.get('events',[]))
 if q.exists():count['fine_detail_corrections']+=len(json.load(open(q)).get('corrections',[]))
count['contact_status_counts']=dict(count['contact_status_counts']);stamp=datetime.datetime.now(datetime.timezone.utc).isoformat();data={'updated_utc':stamp,'grade_rubric':{'A':'Compelling useful experience possible now within statedscope','B':'Useful with visibility/context constraints','C':'Exploratory; needs better data, labeling or evaluation','D':'Reliability unproven, untapped positive cases or observed failures; not a claimimpossibleinprinciple'},'counts':count,'capabilities':[dict(zip(['capability','grade','status','works','constraint','evidence'],x)) for x in GRADES]};(D/'grades.json').write_text(json.dumps(data,indent=2))
experiences=[('The exchange microscope','Slow down a real exchange; show actor, visible response and uncertainty beside native frames. Expose corrected labels rather than hide the audit. Constrain it to short reviewed exchanges.'),('The motion playground','Toggle footage and figure-only animation on clear standing sequences; export candidate movement data. Make hands/feet/face optional detail, and abstain on hidden or mixed bodies.'),('The style time machine','Compare phase/visibility-matched McGregor windows across eras, with direct clips and observable-exposure denominators. Let the user inspect fluidity and repertoire before making any statistical career claim.'),('The prediction arcade','Ask what key event will happen, display causal probabilities, then reveal the next exchange. Treat model failures as part of the learning experience; reliable early warning is not established.')]
text='MMA RESEARCH ASSESSMENT\nSnapshot '+stamp+'\n\nMy take: the strongest current foundation is a visual evidence laboratory. It can support entertaining motion studies, exchange explanations, style comparison, searchable observations and prediction experiments without committing to one product. The useful asset is traceable, uncertainty-aware data. Dense review demonstrably changes labels; more detailed anatomy and better prediction are not automatic consequences.\n\nGrades concern usable capability under the stated constraints, not benchmark performance. A=useful now; B=constrained useful; C=exploratory; D=unproven/unsolved or positive detection untested.\n\n'
for cap,g,status,works,con,e in GRADES:text+=f'{g} — {cap}: {status}\n{works}\nConstraint / next need: {con}\nEvidence: {e}\n\n'
text+='DELIGHTFUL EXPERIENCES TO KEEP OPEN\n\n'+'\n\n'.join(n+'\n'+s for n,s in experiences)+'\n\nNEXT SCIENTIFIC GOALS\n\n1. Build an observable standing-exchange dataset with both committed attempts and genuinely quiet/probing negative windows. Freeze definitions, report unknowns and onset intervals, use independent dense review, and distinguish visible contact from hidden endpoints. Same-model agreement is not expert ground truth.\n2. Expand the longitudinal style study across comparable bouts, phases, distance, angle and round context. Keep early/latest availability explicit. Match exposure and quantify sampling sensitivity before claiming a career trend. More labels help here; camera/perspective controls are essential.\n3. Evaluate key-moment warning on many independent takedown, reversal and submission episodes plus matched negative windows. Split by bout and calendar, and forecast from causal observations only. Compare phase/recent-event persistence, rich semantics, pose, historical-fighter memory and dense causal reviews. Historical outcomes must precede target footage. No training is needed for these initial tests.\n4. Improve ground anatomy through part-specific temporal ownership and multiple candidate views. Keep supported head/glove/knee evidence local. More labels cannot reveal a contact or joint that is hidden in every frame; better views or specialized models are needed.\n\nNo new model was trained. All vision and language annotations are model-reviewed, with uncertainty and exact input provenance retained.\n'
prediction_summary = """PREDICTION BY PHASE AND STRIKE TYPE

These tiny selected cases are feasibility probes, not population accuracy estimates. Forecasts receive annotated past sequences only, ending at cutoff; labels improve as new past observations arrive. Separate future frames provide references. No model was trained.

Standing punches: 1 positive, 1 negative, 2 unknown; one correct alert and one false alert. Standing kicks: same counts and alert pattern. These do not establish reliable prediction. Standing knee/elbow has four negatives and no positive, so positive ability remains untested.
Clinch punches: 2 positives, 0 negatives, 2 unknown; both positives missed. Clinch knee/elbow: same counts, both missed. Clinch kicks: all four unknown.
Ground strikes: frozen references 6 positives, 0 negatives, 2 unknown; 4 alerts and 2 misses. Targeted native review leaves 3 positives, 0 negatives, 5 unknown; only 1 alert and 2 misses. This sensitivity analysis is selected and uses the same model family, not an expert gold standard. With no negatives, neither view tests false alarms.
Takedown: all three overlapping cutoffs before one selected episode missed. Reversal: both positive cutoffs before one selected established-control episode missed; earliest cutoff unclear because control establishes outside its horizon. Submission: no verified positive episode, so detection or prediction success is untested.

Dense causal review: two independent Sol reviews of 48 strictly past native frames per cutoff still missed both selected key events. Takedown probabilities 19%, 8%, 10%; reversal probabilities 17%, 17%, 24%. Same-model agreement does not establish truth. Sampling, annotation schema and two-reviewer bundle changed jointly, so this cannot isolate a frame-rate effect.

Interpretation: visible standing observations can support useful exploration now. Ground anatomy and event boundaries are substantially more uncertain. Better retrospective descriptions alone have not established useful anticipation. The next leap requires independent episodes, quiet negative controls, matched visibility and stronger temporal ownership/state representations.

"""
text += prediction_summary
(D/'report.txt').write_text(text)
esc=html.escape;cards=''.join(f'<article><div class="grade">{esc(g)}</div><div><h3>{esc(cap)}</h3><strong>{esc(status)}</strong><p>{esc(works)}</p><p class="muted">{esc(con)}</p><a href="{esc(e)}">Inspect evidence ↗</a></div></article>' for cap,g,status,works,con,e in GRADES)
h='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MMA / Possibility map</title><style>body{background:#10171c;color:#edf0e9;font:15px/1.6 system-ui;margin:0}main{max-width:1150px;margin:auto;padding:32px}a{color:#22d3ee}h1{font-size:clamp(38px,5vw,62px);line-height:1.1;letter-spacing:-2px;font-weight:550}h2,h3{font-weight:550}p,.muted{color:#a3b0b7}article{display:grid;grid-template-columns:65px 1fr;gap:20px;background:#18232a;border:1px solid #35434a;padding:24px;margin:16px 0;border-radius:10px}.grade{font-size:32px;color:#22d3ee}.ideas{display:grid;grid-template-columns:1fr 1fr;gap:16px}.idea{background:#18232a;padding:22px;border-top:2px solid #fb7185}.note{border-left:2px solid #fb7185;background:#1b252b;padding:15px 20px}pre{white-space:pre-wrap;font:13px/1.7 system-ui}@media(max-width:650px){main{padding:18px}.ideas{grid-template-columns:1fr}article{grid-template-columns:45px 1fr;padding:17px}}</style></head><body><main><a href="../index.html">← Evidence laboratory</a><h1>A map of the possibilities.</h1><p>What can be wonderful with current technology, where the labels fail, and which improvements would actually matter.</p><div class="note">Grades describe usable scope, not certified accuracy. A useful experience can coexist with weak predictive performance. Unknown labels stay visible; a visually detailed skeleton can still have incorrect limb ownership.</div><h2>Four experiences worth keeping open</h2><div class="ideas">__IDEAS__</div><h2>Capability grades</h2>__CARDS__<h2>Prediction by phase and strike type</h2><pre>__PREDICTION__</pre><p><a href="../key_moments/subtypes/index.html">Inspect every subtype forecast and its frames ↗</a> · <a href="../key_moments/dense_prefix/index.html">Dense past stress test ↗</a></p><h2>Next scientific goals</h2><pre>__NEXT__</pre><p>__STAMP__ · <a href="report.txt">Read full assessment</a> · <a href="grades.json">Structured grades</a> · <a href="../key_moments/subtypes/index.html">Prediction by strike type and phase</a></p></main></body></html>'''
ideas=''.join('<div class="idea"><h3>'+esc(n)+'</h3><p>'+esc(s)+'</p></div>' for n,s in experiences);next_text=text.split('NEXT SCIENTIFIC GOALS\n\n')[1].split('PREDICTION BY PHASE AND STRIKE TYPE')[0];(D/'index.html').write_text(h.replace('__IDEAS__',ideas).replace('__CARDS__',cards).replace('__NEXT__',esc(next_text)).replace('__STAMP__',esc(stamp)).replace('__PREDICTION__',esc(prediction_summary)));print('ASSESSMENT',count)
