from pathlib import Path
import json
O=Path('outputs/expanded');P=O/'causal_v2';cases=[]
for c,t in [(c,t) for c in 'EFGH' for t in [4,8,12,16]]:
 cases.append({'clip':c,'cutoff':t,'reference':json.load(open(P/'references'/f'{c}_{t}.json')),'past':[a for a in json.load(open(P/'observations'/f'{c}.json')) if a['end']<=t],'predictions':{k:json.load(open(P/'predictions'/f'{c}_{t}_{k}.json')) for k in ['coarse_history','rich_history','rich_pose_history']}})
html='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MMA causal preview</title><style>body{margin:0;background:#10171c;color:#edf0e9;font:15px/1.5 system-ui}main{max-width:1200px;margin:auto;padding:28px}h1{font-size:38px;letter-spacing:-1px;font-weight:550}p{color:#a3b0b7}a{color:#22d3ee}video{width:100%;aspect-ratio:16/9;background:black}.grid{display:grid;grid-template-columns:1.1fr 1fr;gap:24px}button,select{font:inherit;background:#1c2a33;color:#edf0e9;border:1px solid #485e69;border-radius:6px;padding:8px;margin:0 6px 8px 0}.bar{display:grid;grid-template-columns:145px 1fr 40px;gap:8px;align-items:center;font-size:13px;margin:7px 0}.track{height:8px;background:#31444f}.fill{height:8px;background:#22d3ee}pre{white-space:pre-wrap;font:12px/1.5 monospace}.card{padding:20px;background:#18232a;border-radius:10px}#ref{border-left:2px solid #fb7185;padding:12px 16px;margin-top:18px}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style></head><body><main><a href="../index.html">← Expanded laboratory</a><h1>Only the past goes into the prediction.</h1><p>16-case exploratory study on newly annotated sequences. References come from separate Sol image reviews; they are model-reviewed, not expert truth. Seven first-action references remain unclear and are excluded from scoring.</p><select id="case" aria-label="Case"></select><select id="condition" aria-label="Prediction inputs"><option value="coarse_history">Phase + visibility</option><option value="rich_history" selected>Rich past observations</option><option value="rich_pose_history">Rich past + pose estimates</option></select><div class="grid"><div class="card"><video id="video" controls muted playsinline preload="metadata"></video><button id="past">Play observed prefix</button><button id="reveal">Reveal next 4 seconds</button><div id="ref" hidden></div><details><summary>Inspect past annotations</summary><pre id="labels"></pre></details></div><div class="card"><h2>Predicted phase</h2><div id="phase"></div><h2>Predicted first new action</h2><div id="action"></div><p id="reason"></p><details><summary>Inspect prediction data</summary><pre id="raw"></pre></details></div></div><p>All variants got the phase right in 16/16 cases; phase persistence also got 16/16. First action: coarse 0/9, rich text 2/9, rich text + pose 1/9. Rich text gave lower action probability error here; adding pose estimates did not improve on rich text. Nine action references are scoreable; seven remain unclear. Cases are nested inside three bouts and prove no general advantage.</p><a href="scores.json">Scores</a> · <a href="paired_deltas.json">Paired differences</a> · <a href="protocol.json">Protocol</a></main><script>
const DATA=__DATA__,$=id=>document.getElementById(id),v=$('video');let end=4;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const nice=s=>s.replaceAll('_',' ');function bars(obj){let sum=Object.values(obj).reduce((a,b)=>a+b,0);return Object.entries(obj).map(([k,p])=>`<div class="bar"><span>${nice(k)}</span><div class="track"><div class="fill" style="width:${100*p/sum}%"></div></div><span>${(100*p/sum).toFixed(0)}%</span></div>`).join('')}$('case').innerHTML=DATA.map((d,i)=>`<option value="${i}">Clip ${d.clip} · predict after ${d.cutoff}s</option>`).join('');function render(){v.pause();let d=DATA[Number($('case').value)],p=d.predictions[$('condition').value];if(!v.src.endsWith('/'+d.clip+'.mp4'))v.src='../clips/'+d.clip+'.mp4';end=d.cutoff;v.currentTime=0;$('ref').hidden=true;$('phase').innerHTML=bars(p.end_phase_probabilities);$('action').innerHTML=bars(p.first_action_probabilities);$('reason').textContent=p.rationale;$('labels').textContent=JSON.stringify(d.past,null,2);$('raw').textContent=JSON.stringify(p,null,2)}$('case').onchange=render;$('condition').onchange=render;$('past').onclick=()=>{let d=DATA[Number($('case').value)];end=d.cutoff;v.currentTime=0;v.play()};$('reveal').onclick=()=>{let d=DATA[Number($('case').value)];end=d.cutoff+4;v.currentTime=d.cutoff;$('ref').hidden=false;$('ref').textContent='Separate reference: phase '+d.reference.end_phase+'; first new action '+nice(d.reference.first_new_committed_action)+'. '+(d.reference.first_action_evidence||'');v.play()};v.ontimeupdate=()=>{if(v.currentTime>=end)v.pause()};render();
</script></body></html>'''
(P/'index.html').write_text(html.replace('__DATA__',json.dumps(cases).replace('</','<\\/')))
print('Causal preview viewer built')
