import json
from pathlib import Path
O=Path('outputs/expanded/mcgregor');P=O/'pilot';manifest=json.load(open(P/'manifest.json'));data=[]
for r in manifest:
 p=P/'labels'/f"{r['anonymous_id']}.json";m=P/'audit'/f"{r['anonymous_id']}.metadata.json"
 if p.exists() and m.exists():data.append({'sample':r,'label':json.load(open(p))})
html='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>McGregor movement evidence</title><style>body{margin:0;background:#10171c;color:#edf0e9;font:15px/1.5 system-ui}main{max-width:1400px;margin:auto;padding:30px}h1{font-size:42px;font-weight:550;letter-spacing:-1px}a{color:#22d3ee}p{color:#a3b0b7}select{font:inherit;background:#1c2a33;color:#edf0e9;border:1px solid #485e69;padding:9px;border-radius:6px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card{background:#18232a;border:1px solid #35434a;border-radius:12px;padding:18px}.card img{width:100%;display:block;margin:12px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.5 monospace}summary{cursor:pointer;color:#22d3ee}.note{border-left:2px solid #fb7185;padding:12px 18px;background:#1b252b}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style></head><body><main><a href="../index.html">← Expanded laboratory</a><h1>How does his movement change?</h1><p>Start with comparable visible evidence, not a style label. The karate-to-boxing idea is a hypothesis. This first pilot contains 12 registered eight-second windows nested inside two bouts; it cannot establish a career trajectory.</p><p class="note">Early: 2013 Holloway bout. Late: 2021 Poirier bout. Opponents, range, phase, fatigue, broadcast framing and camera perspective differ. Systematic source-time sampling retains nonfight and ground windows as exclusions. Clothing and wrist tape are verified separately for each bout; they are not universal identities.</p><select id="era" aria-label="Evidence group"><option value="">All registered windows</option><option value="BCOy-PG8EIw">2013 footage</option><option value="6yu2AWK4rxo">2021 footage</option></select><p><a href="pilot/bout_summary.json">Current checked metric summary</a> · <a href="protocol.txt">Career study protocol</a> · <a href="source_catalog_luna.json">Official source timeline and gaps</a></p><div class="grid" id="cards"></div><script>
const DATA=__DATA__,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function render(){let era=document.getElementById('era').value;document.getElementById('cards').innerHTML=DATA.filter(d=>!era||d.sample.source===era).map(d=>{let id=d.sample.anonymous_id,l=d.label;return `<article class="card"><strong>${id} · ${d.sample.source==='BCOy-PG8EIw'?'2013':'2021'} · source ${d.sample.start}s</strong><p>Live fight: ${esc(l.live_fight)} · target visibility: ${esc(l.target_identity_visibility)} · ${esc(l.target_clothing)}</p><a href="pilot/native/${id}-00.jpg"><img loading="lazy" src="pilot/native/${id}-00.jpg" alt="${id} full native opening frame with feet preserved"></a><p>${esc(JSON.stringify(l.phases))}</p><details><summary>Inspect movement and action observations</summary><pre>${esc(JSON.stringify(l,null,2))}</pre></details><details><summary>Full native anchor frames</summary>${['16','31'].map(n=>`<a href="pilot/native/${id}-${n}.jpg"><img loading="lazy" src="pilot/native/${id}-${n}.jpg" alt="${id} native frame ${n}"></a>`).join('')}</details></article>`}).join('')}document.getElementById('era').onchange=render;render();
</script></main></body></html>'''
(O/'index.html').write_text(html.replace('__DATA__',json.dumps(data).replace('</','<\\/')))
print('McGregor evidence viewer',len(data),'model-reviewed windows')
